name: "Storybook Tests"

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      - name: Install Playwright
        run: bunx playwright install --with-deps
      - name: Build Storybook
        run: bunx --cwd react-aria-carousel build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          cd react-aria-carousel \
          "npx concurrently -k -s first -n \"SB,TEST\" -c \"magenta,blue\"" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && bun run test-storybook"
